#!/usr/bin/env bash

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y
udo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemctl status nginx
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
