#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
sudo apt-get update
sudo apt-get install haproxy -y
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 172490-web-01 54.160.64.210:80 check
        server 172490-web-02 100.25.202.36:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
