#!/usr/bin/env bash

# Install HAproxy
sudo apt update
sudo apt install haproxy -y

# Configure HAproxy
sudo sed -i '35 a \\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back' /etc/haproxy/haproxy.cfg
sudo sed -i '40 a \\nbackend http_back\n\tbalance roundrobin\n\tserver web-01 54.160.64.210:80 check\n\tserver web-02 100.25.2.15:80 check' /etc/haproxy/haproxy.cfg
sudo sed -i '10 i  ENABLED=1' /etc/default/haproxy

# Restart HAproxy
sudo service haproxy restart
